version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrms_db
      MYSQL_USER: hrms_user
      MYSQL_PASSWORD: hrms_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hrms-network

  backend:
    build:
      context: ./Backend_hrms
    container_name: hrms-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrms_db
      SPRING_DATASOURCE_USERNAME: hrms_user
      SPRING_DATASOURCE_PASSWORD: hrms_pass
    networks:
      - hrms-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hrms-network
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  hrms-network:
    driver: bridge

volumes:
  mysql-data:
