version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: hrms_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrmsportal         # Database name matching backend config
      MYSQL_USER: hrms_user
      MYSQL_PASSWORD: hrms_pass123       # Password to match backend
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hrms-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    image: mohancc1/backend:latest
    container_name: hrms_backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrmsportal   # Corrected DB name
      SPRING_DATASOURCE_USERNAME: hrms_user
      SPRING_DATASOURCE_PASSWORD: hrms_pass123
    networks:
      - hrms-network

  frontend:
    image: mohancc1/frontend:latest
    container_name: hrms_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hrms-network
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  hrms-network:
    driver: bridge

volumes:
  mysql-data:
