version: '3.8'

services:
  mysql-service:
    image: mysql:8.0
    container_name: hrms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hrms_db"        # from first file
      MYSQL_USER: "hrms_user"          # from first file
      MYSQL_PASSWORD: "hrms_pass"      # from first file
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      timeout: 5s

  springboot-service:
    image: mohancc1/backend:latest
    container_name: hrms_backend
    ports:
      - "8080:8080"
    depends_on:
      mysql-service:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/hrms_db
      SPRING_DATASOURCE_USERNAME: hrms_user
      SPRING_DATASOURCE_PASSWORD: hrms_pass
    networks:
      - mynetwork

  frontend:
    image: mohancc1/frontend:latest
    container_name: hrms_frontend
    ports:
      - "4200:80"
    depends_on:
      - springboot-service
    networks:
      - mynetwork
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  mynetwork:

volumes:
  mysql-data:
