version: '3.8'

services:
  mysql-service:
    image: mysql:8.0
    container_name: hrms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hrmsportal"   # 👈 matches application.properties
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      timeout: 5s

  springboot-service:
    image: mohancc1/backend:latest
    container_name: hrms_backend
    ports:
      - "8080:8080"
    depends_on:
      mysql-service:
        condition: service_healthy
    networks:
      - mynetwork

  frontend:
    image: mohancc1/frontend:latest
    container_name: hrms_frontend
    ports:
      - "4200:80"
    depends_on:
      - springboot-service
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql-data:
